### ISSUE TITLE
Not downloading subtitles

### ISSUE THREAD

**Issue by stepansanda** [mikrop/TitulkyCom.bundle#3]
Hi, I downloaded and put it into the Plex plugin folder. Then I set it in Plex and fill my username and password. Unfortunately, it is not downloading any subtitles from tittulky.com 

Is this plugin still working correctly?

**Comment by petrmenzel** [comment]
I think that it does not work.

**Comment by mikrop** [comment]
Hello, the plugin is not ready yet, it's only a skeleton of the project. I am sorry.

**Comment by stepansanda** [comment]
Do not apologize. Hope that it will be finished one day, it will be very helpful for lots of people I can imagine 👍
